services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    command:
      [ "sh", "-c", "until nc -z -v -w30 mysql 3306; do echo 'waiting for database connection...'; sleep 5; done; ./main" ]

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
